DROP TABLE IF EXISTS t_stale;
CREATE TABLE t_stale (
    id       BIGINT      NOT NULL AUTO_INCREMENT,
    item     VARCHAR(100) NOT NULL,
    qty      INT         NOT NULL DEFAULT 0,
    price    DECIMAL(10,2) NOT NULL,
    updated_at DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
