-- good.sql: AUTO_RANDOM / SHARD_ROW_ID_BITS 避免热点

-- 1. AUTO_RANDOM 表的 Region 分布（ID 被哈希分散到多个 Region）
SHOW TABLE t_auto_random REGIONS;

-- 2. SHARD_ROW_ID_BITS 表的 Region 分布
SHOW TABLE t_shard_row REGIONS;

-- 3. 使用 AUTO_RANDOM 批量插入（写入分散到多个 TiKV 节点）
INSERT INTO t_auto_random (name, val)
SELECT CONCAT('user_', seq), FLOOR(RAND() * 1000)
FROM (SELECT @rownum := @rownum + 1 AS seq FROM
      (SELECT 0 UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT @rownum := 0) r
) t LIMIT 1000;

-- 4. SHARD_ROW_ID_BITS 表批量插入
INSERT INTO t_shard_row (name, val)
SELECT CONCAT('user_', seq), FLOOR(RAND() * 1000)
FROM (SELECT @rownum := @rownum + 1 AS seq FROM
      (SELECT 0 UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
      (SELECT 0 UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
      (SELECT @rownum := 0) r
) t LIMIT 1000;

-- 5. 对比三张表的数据量
SELECT 'AUTO_INCREMENT' AS tbl, COUNT(*) FROM t_auto_inc
UNION ALL
SELECT 'AUTO_RANDOM', COUNT(*) FROM t_auto_random
UNION ALL
SELECT 'SHARD_ROW_ID_BITS', COUNT(*) FROM t_shard_row;
